### ISSUE TITLE
Add policy API

### ISSUE THREAD

**Issue by ror6ax** [nokia/vault_keystone_plugin#3]
Add methods from https://developer.openstack.org/api-ref/identity/v3/#policies

**Comment by klebervirgilio** [comment]
@ror6ax could you please gimme the guidelines? I really want to get this done. :)

**Comment by ror6ax** [comment]
Sure, take it. 
Have a look at existing implemented methods of Keystone API, like users in https://developer.openstack.org/api-ref/identity/v3/#users

You'd need to register route in plugin/backend.go and then implement the methods themselves in new file `plugin/policies.go`

**Comment by ror6ax** [comment]
Hi @klebervirgilio , need help with this?

**Comment by ror6ax** [comment]
Closing due to policies being marked as deprecated in v3 API.
