### ISSUE TITLE
Add regions API

### ISSUE THREAD

**Issue by ror6ax** [nokia/vault_keystone_plugin#4]
Add methods from https://developer.openstack.org/api-ref/identity/v3/#regions

**Comment by ndedic** [comment]
I can look at implementing regions and/or policy API this week. I will have to set up Vault locally though.

**Comment by ror6ax** [comment]
@ndedic - that would be awesome!

**Comment by ror6ax** [comment]
Please note that policy is handled by another issue and there is a potential contributor there also.

**Comment by ndedic** [comment]
ok, noted :)

**Comment by ndedic** [comment]
Hi @ror6ax , I have managed to get OpenStack up and running locally as well as Vault, however when I try to mount plugin to a path I get the following error:
```
$ ./vault mount -path=keystone -plugin-name=vault_keystone_plugin plugin
Mount error: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/mounts/keystone
Code: 400. Errors:

* Incompatible API version with plugin. Plugin version: 3, Ours: 2
```
I am running Go 1.9 on Ubuntu 16.10

**Comment by ror6ax** [comment]
You seem to have compiled the plugin against latest Vault code, but you are using the older binary. Try using latest binary.

**Comment by ndedic** [comment]
That didn't work :/

**Comment by ror6ax** [comment]
Can you show me how you build the plugin and how do you start Vault please?

**Comment by ndedic** [comment]
1. Build the plugin:
- clone the repo
- go get dependencies (as per readme and antything else that is missing, e.g. testify/assert in my case)
- run plugin tests (`cd plugins && go test`) - optional
- `go build -o vault_keystone_plugin .`

2. Start Vault server:
- download Vault Linux package (https://www.vaultproject.io/downloads.html)
- create config.json with only one property defined, `plugin_directory = "."`
- export env var: `export VAULT_ADDR=http://127.0.0.1:8200`
- start server in dev mode: `./vault server -dev -config=config.json`

3. Register and mount plugin
- move binary `vault_keystone_plugin` (compiled in step 1) to the same folder where Vault server package is located and run:
```
sha256sum vault_keystone_plugin
vault write sys/plugins/catalog/vault_keystone_plugin sha_256="<SHA from the previous step>" command="vault_keystone_plugin"
```
results in success
- mount plugin to a path: `vault mount -path=keystone -plugin-name=vault_keystone_plugin plugin`
fails as described in a comment above

**Comment by ndedic** [comment]
#8
